<?php
//
// File generated by Dolibarr installer 18.0.3 on 29 Nov. 2023
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='https://dev.zopa.dhagpo-kundreul-ling.org:443/dolibarr';
$dolibarr_main_document_root='/home/xjydenq/dev.zopa.dhagpo-kundreul-ling.org/dolibarr';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/home/xjydenq/dev.zopa.dhagpo-kundreul-ling.org/dolibarr/custom';
$dolibarr_main_data_root='/home/xjydenq/dev.zopa.dhagpo-kundreul-ling.org/dolibarr/documents';
$dolibarr_main_db_host='da46046-002.eu.clouddb.ovh.net:35585';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='DBzopaktldev';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='Uzopaktldev';
$dolibarr_main_db_pass='cMbgh5dK7uJ8g4fsKfm6';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_unicode_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore, clamdscan, clamscan.exe';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='a2c2bf5f2162b5df59dc04874e0a19ae';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
